apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-application
  name: nginx-application
  namespace: nginx-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-application
  template:
    metadata:
      labels:
        app: nginx-application
    spec:
      containers:
      - image: quay.io/sharma_a38/nginx:latest
        name: nginx-application
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-application
  namespace: nginx-application
  labels:
    app: nginx-application
spec:
  type: NodePort
  selector:
    app: nginx-application
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 32090
